name: CKEditor
author: inviz
copyright: Frederico Knabben 
category: Interface
tags: [wysiwyg, editor]
docs: http://docs.cksource.com
demo: ckeditor.com/demo
sources: 
 - "Source/core/_bootstrap.js"
 - "Source/core/ckeditor.js"
 - "Source/core/ckeditor_base.js"
 - "Source/core/ckeditor_basic.js"
 - "Source/core/command.js"
 - "Source/core/commanddefinition.js"
 - "Source/core/config.js"
 - "Source/core/dataprocessor.js"
 - "Source/core/dom/comment.js"
 - "Source/core/dom/document.js"
 - "Source/core/dom/documentfragment.js"
 - "Source/core/dom/domobject.js"
 - "Source/core/dom/element.js"
 - "Source/core/dom/elementpath.js"
 - "Source/core/dom/event.js"
 - "Source/core/dom/node.js"
 - "Source/core/dom/nodelist.js"
 - "Source/core/dom/range.js"
 - "Source/core/dom/rangelist.js"
 - "Source/core/dom/text.js"
 - "Source/core/dom/walker.js"
 - "Source/core/dom/window.js"
 - "Source/core/dom.js"
 - "Source/core/dtd.js"
 - "Source/core/editor.js"
 - "Source/core/editor_basic.js"
 - "Source/core/env.js"
 - "Source/core/event.js"
 - "Source/core/eventInfo.js"
 - "Source/core/focusmanager.js"
 - "Source/core/htmlparser/basicwriter.js"
 - "Source/core/htmlparser/cdata.js"
 - "Source/core/htmlparser/comment.js"
 - "Source/core/htmlparser/element.js"
 - "Source/core/htmlparser/filter.js"
 - "Source/core/htmlparser/fragment.js"
 - "Source/core/htmlparser/text.js"
 - "Source/core/htmlparser.js"
 - "Source/core/lang.js"
 - "Source/core/loader.js"
 - "Source/core/plugindefinition.js"
 - "Source/core/plugins.js"
 - "Source/core/resourcemanager.js"
 - "Source/core/scriptloader.js"
 - "Source/core/skins.js"
 - "Source/core/themes.js"
 - "Source/core/tools.js"
 - "Source/core/ui.js"
 - "Source/lang/_languages.js"
 - "Source/lang/af.js"
 - "Source/lang/ar.js"
 - "Source/lang/bg.js"
 - "Source/lang/bn.js"
 - "Source/lang/bs.js"
 - "Source/lang/ca.js"
 - "Source/lang/cs.js"
 - "Source/lang/cy.js"
 - "Source/lang/da.js"
 - "Source/lang/de.js"
 - "Source/lang/el.js"
 - "Source/lang/en-au.js"
 - "Source/lang/en-ca.js"
 - "Source/lang/en-gb.js"
 - "Source/lang/en.js"
 - "Source/lang/eo.js"
 - "Source/lang/es.js"
 - "Source/lang/et.js"
 - "Source/lang/eu.js"
 - "Source/lang/fa.js"
 - "Source/lang/fi.js"
 - "Source/lang/fo.js"
 - "Source/lang/fr-ca.js"
 - "Source/lang/fr.js"
 - "Source/lang/gl.js"
 - "Source/lang/gu.js"
 - "Source/lang/he.js"
 - "Source/lang/hi.js"
 - "Source/lang/hr.js"
 - "Source/lang/hu.js"
 - "Source/lang/is.js"
 - "Source/lang/it.js"
 - "Source/lang/ja.js"
 - "Source/lang/ka.js"
 - "Source/lang/km.js"
 - "Source/lang/ko.js"
 - "Source/lang/lt.js"
 - "Source/lang/lv.js"
 - "Source/lang/mn.js"
 - "Source/lang/ms.js"
 - "Source/lang/nb.js"
 - "Source/lang/nl.js"
 - "Source/lang/no.js"
 - "Source/lang/pl.js"
 - "Source/lang/pt-br.js"
 - "Source/lang/pt.js"
 - "Source/lang/ro.js"
 - "Source/lang/ru.js"
 - "Source/lang/sk.js"
 - "Source/lang/sl.js"
 - "Source/lang/sr-latn.js"
 - "Source/lang/sr.js"
 - "Source/lang/sv.js"
 - "Source/lang/th.js"
 - "Source/lang/tr.js"
 - "Source/lang/uk.js"
 - "Source/lang/vi.js"
 - "Source/lang/zh-cn.js"
 - "Source/lang/zh.js"
 - "Source/plugins/a11yhelp/dialogs/a11yhelp.js"
 - "Source/plugins/a11yhelp/lang/en.js"
 - "Source/plugins/a11yhelp/lang/he.js"
 - "Source/plugins/a11yhelp/plugin.js"
 - "Source/plugins/about/dialogs/about.js"
 - "Source/plugins/about/plugin.js"
 - "Source/plugins/adobeair/plugin.js"
 - "Source/plugins/ajax/plugin.js"
 - "Source/plugins/autogrow/plugin.js"
 - "Source/plugins/basicstyles/plugin.js"
 - "Source/plugins/bbcode/plugin.js"
 - "Source/plugins/bidi/plugin.js"
 - "Source/plugins/blockquote/plugin.js"
 - "Source/plugins/button/plugin.js"
 - "Source/plugins/clipboard/dialogs/paste.js"
 - "Source/plugins/clipboard/plugin.js"
 - "Source/plugins/colorbutton/plugin.js"
 - "Source/plugins/colordialog/dialogs/colordialog.js"
 - "Source/plugins/colordialog/plugin.js"
 - "Source/plugins/contextmenu/plugin.js"
 - "Source/plugins/devtools/lang/en.js"
 - "Source/plugins/devtools/plugin.js"
 - "Source/plugins/dialog/dialogDefinition.js"
 - "Source/plugins/dialog/plugin.js"
 - "Source/plugins/dialogadvtab/plugin.js"
 - "Source/plugins/dialogui/plugin.js"
 - "Source/plugins/div/dialogs/div.js"
 - "Source/plugins/div/plugin.js"
 - "Source/plugins/docprops/dialogs/docprops.js"
 - "Source/plugins/docprops/plugin.js"
 - "Source/plugins/domiterator/plugin.js"
 - "Source/plugins/editingblock/plugin.js"
 - "Source/plugins/elementspath/plugin.js"
 - "Source/plugins/enterkey/plugin.js"
 - "Source/plugins/entities/plugin.js"
 - "Source/plugins/fakeobjects/plugin.js"
 - "Source/plugins/filebrowser/plugin.js"
 - "Source/plugins/find/dialogs/find.js"
 - "Source/plugins/find/plugin.js"
 - "Source/plugins/flash/dialogs/flash.js"
 - "Source/plugins/flash/plugin.js"
 - "Source/plugins/floatpanel/plugin.js"
 - "Source/plugins/font/plugin.js"
 - "Source/plugins/format/plugin.js"
 - "Source/plugins/forms/dialogs/button.js"
 - "Source/plugins/forms/dialogs/checkbox.js"
 - "Source/plugins/forms/dialogs/form.js"
 - "Source/plugins/forms/dialogs/hiddenfield.js"
 - "Source/plugins/forms/dialogs/radio.js"
 - "Source/plugins/forms/dialogs/select.js"
 - "Source/plugins/forms/dialogs/textarea.js"
 - "Source/plugins/forms/dialogs/textfield.js"
 - "Source/plugins/forms/plugin.js"
 - "Source/plugins/horizontalrule/plugin.js"
 - "Source/plugins/htmldataprocessor/plugin.js"
 - "Source/plugins/htmlwriter/plugin.js"
 - "Source/plugins/iframe/dialogs/iframe.js"
 - "Source/plugins/iframe/plugin.js"
 - "Source/plugins/iframedialog/plugin.js"
 - "Source/plugins/image/dialogs/image.js"
 - "Source/plugins/image/plugin.js"
 - "Source/plugins/indent/plugin.js"
 - "Source/plugins/justify/plugin.js"
 - "Source/plugins/keystrokes/plugin.js"
 - "Source/plugins/link/dialogs/anchor.js"
 - "Source/plugins/link/dialogs/link.js"
 - "Source/plugins/link/plugin.js"
 - "Source/plugins/list/plugin.js"
 - "Source/plugins/listblock/plugin.js"
 - "Source/plugins/liststyle/dialogs/liststyle.js"
 - "Source/plugins/liststyle/plugin.js"
 - "Source/plugins/maximize/plugin.js"
 - "Source/plugins/menu/plugin.js"
 - "Source/plugins/menubutton/plugin.js"
 - "Source/plugins/newpage/plugin.js"
 - "Source/plugins/pagebreak/plugin.js"
 - "Source/plugins/panel/plugin.js"
 - "Source/plugins/panelbutton/plugin.js"
 - "Source/plugins/pastefromword/filter/default.js"
 - "Source/plugins/pastefromword/plugin.js"
 - "Source/plugins/pastetext/dialogs/pastetext.js"
 - "Source/plugins/pastetext/plugin.js"
 - "Source/plugins/placeholder/dialogs/placeholder.js"
 - "Source/plugins/placeholder/lang/en.js"
 - "Source/plugins/placeholder/lang/he.js"
 - "Source/plugins/placeholder/plugin.js"
 - "Source/plugins/popup/plugin.js"
 - "Source/plugins/preview/plugin.js"
 - "Source/plugins/print/plugin.js"
 - "Source/plugins/removeformat/plugin.js"
 - "Source/plugins/resize/plugin.js"
 - "Source/plugins/richcombo/plugin.js"
 - "Source/plugins/save/plugin.js"
 - "Source/plugins/scayt/dialogs/options.js"
 - "Source/plugins/scayt/plugin.js"
 - "Source/plugins/selection/plugin.js"
 - "Source/plugins/showblocks/plugin.js"
 - "Source/plugins/showborders/plugin.js"
 - "Source/plugins/smiley/dialogs/smiley.js"
 - "Source/plugins/smiley/plugin.js"
 - "Source/plugins/sourcearea/plugin.js"
 - "Source/plugins/specialchar/dialogs/specialchar.js"
 - "Source/plugins/specialchar/lang/en.js"
 - "Source/plugins/specialchar/plugin.js"
 - "Source/plugins/styles/plugin.js"
 - "Source/plugins/styles/styles/default.js"
 - "Source/plugins/stylescombo/plugin.js"
 - "Source/plugins/stylesheetparser/plugin.js"
 - "Source/plugins/tab/plugin.js"
 - "Source/plugins/table/dialogs/table.js"
 - "Source/plugins/table/plugin.js"
 - "Source/plugins/tableresize/plugin.js"
 - "Source/plugins/tabletools/dialogs/tableCell.js"
 - "Source/plugins/tabletools/plugin.js"
 - "Source/plugins/templates/dialogs/templates.js"
 - "Source/plugins/templates/plugin.js"
 - "Source/plugins/templates/templates/default.js"
 - "Source/plugins/toolbar/plugin.js"
 - "Source/plugins/uicolor/dialogs/uicolor.js"
 - "Source/plugins/uicolor/lang/en.js"
 - "Source/plugins/uicolor/lang/he.js"
 - "Source/plugins/uicolor/plugin.js"
 - "Source/plugins/uicolor/yui/yui.js"
 - "Source/plugins/undo/plugin.js"
 - "Source/plugins/wsc/dialogs/wsc.js"
 - "Source/plugins/wsc/plugin.js"
 - "Source/plugins/wysiwygarea/plugin.js"
 - "Source/plugins/xml/plugin.js"
 - "Source/skins/kama/skin.js"
 - "Source/skins/office2003/skin.js"
 - "Source/skins/v2/skin.js"
 - "Source/themes/default/theme.js"
 - "Source/CKEditor.js"